services:
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: vivabela
      MYSQL_DATABASE: ernany_db
    volumes:
      - ../mysql_data:/var/lib/mysql
